<?php

namespace Inamika\BackEndBundle\Repository;
use Inamika\BackEndBundle\Entity\Maps;
/**
 * MapsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapsRepository extends \Doctrine\ORM\EntityRepository
{
    public function save($stringBase64=null){
        $map = new Maps();
        $map->setContent($stringBase64);
        $map->setMimeType(explode(':', substr($stringBase64, 0, strpos($stringBase64, ';')))[1]);
        $em = $this->getEntityManager();
        $em->persist($map);
        $em->flush();
        return $map;
    }
}
