<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * ProjectUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
