<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * ProjectLevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLevelsRepository extends \Doctrine\ORM\EntityRepository
{
}
