<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * ProjectBlocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectBlocksRepository extends \Doctrine\ORM\EntityRepository
{
}
