<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * SvgDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvgDefinitionsRepository extends \Doctrine\ORM\EntityRepository
{
}
