<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * UnitFeatureDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitFeatureDataRepository extends \Doctrine\ORM\EntityRepository
{
}
