<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * UnitFeaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitFeaturesRepository extends \Doctrine\ORM\EntityRepository
{
}
