api_units:
    path:     /units
    defaults: { _controller: InamikaApiBundle:Units:index }
    methods: [GET]

api_units_get:
    path:     /units/{id}
    defaults: { _controller: InamikaApiBundle:Units:get }
    methods: [GET]

api_units_post:
    path:     /units
    defaults: { _controller: InamikaApiBundle:Units:post }
    methods: [POST]

api_units_import:
    path:     /units/import
    defaults: { _controller: InamikaApiBundle:Units:import }
    methods: [POST]

api_units_logs:
    path:     /units/{id}/logs
    defaults: { _controller: InamikaApiBundle:Units:logs }
    methods: [GET]

api_units_put:
    path:     /units/{id}
    defaults: { _controller: InamikaApiBundle:Units:put }
    methods: [PUT]

api_units_position:
    path:     /units/{id}/position
    defaults: { _controller: InamikaApiBundle:Units:position }
    methods: [PUT]

api_units_delete:
    path:     /units/{id}
    defaults: { _controller: InamikaApiBundle:Units:delete }
    methods: [DELETE]

api_units_export:
    path:     /units_export
    defaults: { _controller: InamikaApiBundle:Units:export }
    methods: [GET]